// Drizzle schema for the D1 database (binding DB).
// After changing this file run `npm run db:generate` and commit ./drizzle.
import { sql } from "drizzle-orm";
import { sqliteTable, text, integer, index, uniqueIndex } from "drizzle-orm/sqlite-core";
import { user } from "./auth-schema";

// Better Auth's own tables (user, session, account, verification, rate_limit).
// Generated by `npm run auth:schema`; do not edit by hand.
export * from "./auth-schema";

const now = sql`(cast(unixepoch('subsecond') * 1000 as integer))`;

export const profiles = sqliteTable("profiles", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  displayName: text("display_name").notNull(),
  phone: text("phone"),
  role: text("role", { enum: ["user", "admin"] }).notNull().default("user"),
  emailNotifications: integer("email_notifications", { mode: "boolean" })
    .notNull()
    .default(true),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(now),
});

export type Profile = typeof profiles.$inferSelect;

export const LISTING_STATUSES = [
  "draft",
  "awaiting_payment", // reserved for a future listing fee, not used yet
  "submitted",
  "changes_requested",
  "approved",
  "live",
  "offer_accepted",
  "sold",
  "rejected",
  "withdrawn",
] as const;
export type ListingStatus = (typeof LISTING_STATUSES)[number];

export const listings = sqliteTable(
  "listings",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    status: text("status", { enum: LISTING_STATUSES }).notNull().default("draft"),

    // The car
    year: integer("year"),
    make: text("make"),
    model: text("model"),
    bodyStyle: text("body_style"),
    engine: text("engine"),
    transmission: text("transmission"),
    drivetrain: text("drivetrain"),
    exteriorColor: text("exterior_color"),
    interiorColor: text("interior_color"),
    mileage: integer("mileage"),
    vin: text("vin"),
    headline: text("headline"),

    // Condition and history
    description: text("description"),
    highlights: text("highlights"),
    knownIssues: text("known_issues"),
    modifications: text("modifications"),
    serviceHistory: text("service_history"),
    ownerCount: integer("owner_count"),
    titleStatus: text("title_status"),
    titleState: text("title_state"),
    recordsOnFile: integer("records_on_file", { mode: "boolean" }).notNull().default(false),
    videoUrl: text("video_url"),

    // Price and contact
    price: integer("price"),
    acceptsOffers: integer("accepts_offers", { mode: "boolean" }).notNull().default(true),
    locationCity: text("location_city"),
    locationState: text("location_state"),
    contactMethod: text("contact_method", { enum: ["messages", "messages_phone"] })
      .notNull()
      .default("messages"),
    contactPhone: text("contact_phone"),

    // Admin controlled
    sellerType: text("seller_type", { enum: ["private", "dealer"] }).notNull().default("private"),
    verifiedSeller: integer("verified_seller", { mode: "boolean" }).notNull().default(false),
    featured: integer("featured", { mode: "boolean" }).notNull().default(false),

    // Review and publishing
    slug: text("slug").unique(),
    cmsItemId: text("cms_item_id"),
    reviewNotes: text("review_notes"),
    reviewerId: text("reviewer_id"),
    submittedAt: integer("submitted_at", { mode: "timestamp_ms" }),
    reviewedAt: integer("reviewed_at", { mode: "timestamp_ms" }),
    publishedAt: integer("published_at", { mode: "timestamp_ms" }),
    soldAt: integer("sold_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(now),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().default(now),
  },
  (t) => [
    index("listings_user_idx").on(t.userId),
    index("listings_status_idx").on(t.status, t.submittedAt),
  ],
);

export type Listing = typeof listings.$inferSelect;

export const listingPhotos = sqliteTable(
  "listing_photos",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listings.id, { onDelete: "cascade" }),
    r2Key: text("r2_key").notNull(),
    position: integer("position").notNull(),
    width: integer("width"),
    height: integer("height"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(now),
  },
  (t) => [index("listing_photos_listing_idx").on(t.listingId, t.position)],
);

export type ListingPhoto = typeof listingPhotos.$inferSelect;

// Every admin action and every CMS publish is logged here.
export const auditLog = sqliteTable(
  "audit_log",
  {
    id: text("id").primaryKey(),
    actorId: text("actor_id"),
    action: text("action").notNull(),
    entity: text("entity").notNull(),
    entityId: text("entity_id").notNull(),
    data: text("data", { mode: "json" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(now),
  },
  (t) => [index("audit_entity_idx").on(t.entity, t.entityId, t.createdAt)],
);

export type AuditEntry = typeof auditLog.$inferSelect;

export const OFFER_STATUSES = ["pending", "countered", "accepted", "declined", "expired", "withdrawn"] as const;
export type OfferStatus = (typeof OFFER_STATUSES)[number];

// A buyer's offer is a row made by "buyer". A seller's counter is a new row
// made by "seller" whose parent is the offer it answers (which becomes "countered").
export const offers = sqliteTable(
  "offers",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listings.id, { onDelete: "cascade" }),
    buyerId: text("buyer_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    madeBy: text("made_by", { enum: ["buyer", "seller"] }).notNull().default("buyer"),
    amount: integer("amount").notNull(),
    message: text("message"),
    status: text("status", { enum: OFFER_STATUSES }).notNull().default("pending"),
    parentOfferId: text("parent_offer_id"),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    respondedAt: integer("responded_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(now),
  },
  (t) => [
    index("offers_listing_idx").on(t.listingId, t.status),
    index("offers_buyer_idx").on(t.buyerId, t.createdAt),
  ],
);

export type Offer = typeof offers.$inferSelect;

export const threads = sqliteTable(
  "threads",
  {
    id: text("id").primaryKey(),
    listingId: text("listing_id")
      .notNull()
      .references(() => listings.id, { onDelete: "cascade" }),
    buyerId: text("buyer_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    sellerId: text("seller_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    lastMessageAt: integer("last_message_at", { mode: "timestamp_ms" }).notNull().default(now),
  },
  (t) => [
    uniqueIndex("threads_listing_buyer_uq").on(t.listingId, t.buyerId),
    index("threads_buyer_idx").on(t.buyerId, t.lastMessageAt),
    index("threads_seller_idx").on(t.sellerId, t.lastMessageAt),
  ],
);

export type Thread = typeof threads.$inferSelect;

export const messages = sqliteTable(
  "messages",
  {
    id: text("id").primaryKey(),
    threadId: text("thread_id")
      .notNull()
      .references(() => threads.id, { onDelete: "cascade" }),
    senderId: text("sender_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    flagged: integer("flagged", { mode: "boolean" }).notNull().default(false),
    flagReason: text("flag_reason"),
    flagReviewedAt: integer("flag_reviewed_at", { mode: "timestamp_ms" }),
    readAt: integer("read_at", { mode: "timestamp_ms" }),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(now),
  },
  (t) => [
    index("messages_thread_idx").on(t.threadId, t.createdAt),
    index("messages_sender_idx").on(t.senderId, t.createdAt),
    index("messages_flagged_idx").on(t.flagged, t.flagReviewedAt),
  ],
);

export type Message = typeof messages.$inferSelect;
