// Drizzle schema for the D1 database (binding DB).
// After changing this file run `npm run db:generate` and commit ./drizzle.
import { sql } from "drizzle-orm";
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { user } from "./auth-schema";

// Better Auth's own tables (user, session, account, verification, rate_limit).
// Generated by `npm run auth:schema`; do not edit by hand.
export * from "./auth-schema";

const now = sql`(cast(unixepoch('subsecond') * 1000 as integer))`;

export const profiles = sqliteTable("profiles", {
  userId: text("user_id")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  displayName: text("display_name").notNull(),
  phone: text("phone"),
  role: text("role", { enum: ["user", "admin"] }).notNull().default("user"),
  emailNotifications: integer("email_notifications", { mode: "boolean" })
    .notNull()
    .default(true),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().default(now),
});

export type Profile = typeof profiles.$inferSelect;
